#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by Django 2.2.12 on 2020-04-20 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('teacher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=6)),
                ('age', models.PositiveSmallIntegerField(default=20)),
                ('city_text', models.CharField(max_length=200)),
                ('school_text', models.CharField(max_length=200)),
                ('teacher_type', models.CharField(choices=[('G', 'Grade'), ('T', 'Topic')], default='G', max_length=5)),
                ('grade', models.CharField(choices=[('1st', 'א'), ('1st', '2')], default='1st', max_length=2)),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
    ]
