# Generated by Django 2.2.12 on 2020-05-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_statusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdata',
            name='status_number',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
