#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by Django 2.2.12 on 2020-04-20 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_id', models.UUIDField(default=uuid.uuid4)),
                ('source_id', models.UUIDField(default=uuid.uuid4)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnairesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 'בכלל לא מתאר אותי'), ('2', 'מתאר אותי במידה מעטה מאוד'), ('3', 'מתאר אותי במידה מעטה'), ('4', 'מתאר אותי במידה בינונית'), ('5', 'מתאר אותי במידה רבה'), ('6', 'מתאר אותי במידה רבה מאוד'), ('7', 'מתאר אותי באופן מלא (לגמרי אני)')], default='4', max_length=200)),
                ('questionnaire_id', models.UUIDField(default=uuid.uuid4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionsData')),
            ],
        ),
    ]
