# Generated by Django 2.2.12 on 2020-04-20 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200421_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_id', models.UUIDField(default=uuid.uuid4)),
                ('source_id', models.UUIDField(default=uuid.uuid4)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
