# Generated by Django 2.2.12 on 2020-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_idlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=200)),
                ('target', models.CharField(default='', max_length=200)),
                ('explanation', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
