# Generated by Django 2.2.12 on 2020-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20200428_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsdata',
            name='target',
            field=models.CharField(choices=[('1', 'self'), ('3', 'teacher_child'), ('2', 'parent_child')], default='1', max_length=200),
        ),
    ]
