# Generated by Django 2.2.12 on 2020-05-04 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20200428_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireexplanation',
            name='source_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='questionnaireexplanation',
            name='target_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='questionsdata',
            name='target',
            field=models.CharField(choices=[('1', 'self'), ('3', 'teacher_child'), ('2', 'parent_child')], default='1', max_length=200),
        ),
    ]
