# Generated by Django 2.2.12 on 2020-04-20 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parentdata',
            name='id',
        ),
        migrations.AddField(
            model_name='childdata',
            name='child_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='parentdata',
            name='parent_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
