# Generated by Django 2.2.12 on 2020-04-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_auto_20200420_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='name_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parentdata',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='parentdata',
            name='name_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
