# Generated by Django 2.2.12 on 2020-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200425_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
